import { test } from 'node:test';
import assert from 'node:assert/strict';
import { calculateSolar } from '../src/lib/calculator.mjs';
const base={region:'inland',orientation:'south',consumption:5000,area:40,tariff:0.16,selfUse:40,unitCost:1300,subsidy:0,exportPrice:0,shade:0};
test('default: discrete panels, energy and financial arithmetic',()=>{const r=calculateSolar(base);assert.equal(r.panelCount,11);assert.equal(r.power,4.95);assert.equal(r.production,5445);assert.equal(r.savings,348.48);assert.equal(r.investment,6435);assert.ok(Math.abs(r.monthly.reduce((a,b)=>a+b,0)-r.production)<0.001);});
test('roof limits capacity and full self-use never exceeds consumption',()=>{const r=calculateSolar({...base,area:5,selfUse:100});assert.equal(r.panelCount,2);assert.equal(r.roofLimited,true);assert.ok(r.area<=5);const large=calculateSolar({...base,selfUse:100});assert.equal(large.used,5000);assert.equal(large.exported,445);});
test('subsidy reduces investment; export value affects benefits',()=>{const a=calculateSolar(base);const b=calculateSolar({...base,subsidy:50,exportPrice:.05});assert.equal(b.investment,a.investment/2);assert.ok(b.savings>a.savings);assert.ok(b.payback<a.payback);});
test('orientation, shade and regional yield change production on a limited roof',()=>{const south=calculateSolar({...base,area:10});const north=calculateSolar({...base,area:10,orientation:'north'});const shade=calculateSolar({...base,area:10,shade:20});const coast=calculateSolar({...base,area:10,region:'dalmatia'});assert.ok(north.production<south.production);assert.ok(Math.abs(shade.production-south.production*.8)<.001);assert.ok(coast.production>south.production);});
test('invalid, non-finite and out-of-bounds input is rejected',()=>{for(const patch of [{consumption:NaN},{area:Infinity},{area:-1},{tariff:0},{subsidy:81},{selfUse:101},{region:'unknown'},{region:'toString'},{orientation:'constructor'},{exportPrice:-.1}])assert.throws(()=>calculateSolar({...base,...patch}));});
